const FormSearchModel = {
  searchFields: {
    question: {
      value: "",
      label: "Question",
      name: "question",
      type: "text",
      placeholder: " search here",
      validate: {
        max: {
          val: 20,
          msg: "try keep it simple",
        },
        min: {
          val: 1,
          msg: "keep typing",
        },
      },
    },

    from: {
      label: "from",
      name: "from",
      type: "date",
      value: "",
      validate: {},
    },
    to: {
      label: "to",
      name: "to",
      type: "date",
      value: "",
      validate: {},
    },
    sources: {
      label: "sources",
      name: "sources",
      type: "text",
      value: "",
      validate: {},
    },

    sortBy: {
      value: "relevancy",
      type: "select",
      label: "Sort By",
      name: "sortBy",
      options: {
        relevancy: {
          label: "relevancy",
          value: "relevancy",
        },
        popularity: {
          label: "popularity",
          value: "popularity",
        },
        // publishedAt: {
        //   label: "published at",
        //   value: "publishedAt",
        // },
      },
      validate: {
        empty: { val: "" || false, msg: "you have to choose one." },
      },
    },
    category: {
      value: "general",
      type: "select",
      name: "category",
      label: "Category",

      options: {
        all: { label: "all categories", value: "" },
        general: {
          label: "general",
          value: "general",
        },
        business: {
          label: " business",
          value: "business",
        },
        entertainment: {
          label: "entertainment",
          value: "entertainment",
        },
        health: {
          label: "health",
          value: "health",
        },
        science: {
          label: "science",
          value: "science",
        },
        sports: {
          label: "sports",
          value: "sports",
        },
        technology: {
          label: "technology",
          value: "technology",
        },
      },
      validate: {
        //   empty: { val: "" || false, msg: "you have to choose one." },
      },
    },
    language: {
      value: "en",
      type: "select",
      label: "language",
      name: "language",
      validate: {},

      options: {
        all: { label: "All Language", value: "", name: "" },
        ar: { label: "Arabic", value: "ar", name: "ar" },
        de: { label: "German", value: "de", name: "de" },
        en: { label: "English", value: "en", name: "en" },
        es: { label: "Spanish", value: "es", name: "es" },
        fr: { label: "French", value: "fr", name: "fr" },
        he: { label: "Hebrew", value: "he", name: "he" },
        it: { label: "Italian", value: "it", name: "it" },
        nl: { label: "Dutch", value: "nl", name: "nl" },
        no: { label: "Norwegian", value: "no", name: "no" },
        pt: { label: "Portuguese", value: "pt", name: "pt" },
        ru: { label: "Russian", value: "ru", name: "ru" },
        sv: { label: "Swedish", value: "sv", name: "sv" },
        ud: { label: "Urdu", value: "ud", name: "ud" },
        zh: { label: "Chinese", value: "zh", name: "zh" },
      },
    },
    country: {
      value: "us",
      type: "select",
      label: "country",
      name: "country",
      validate: {},
      options: {
        all: { name: "All Countries", value: "" },
        ae: { name: "ae", value: "ae", label: "United Arab Emirates" },
        ar: { name: "ar", value: "ar", label: "Argentina" },
        at: { name: "at", value: "at", label: "Austria" },
        au: { name: "au", value: "au", label: "Australia" },
        be: { name: "be", value: "be", label: "Belgium" },
        bg: { name: "bg", value: "bg", label: "Bulgaria" },
        br: { name: "br", value: "br", label: "Brazil" },
        ca: { name: "ca", value: "ca", label: "Canada" },
        ch: { name: "ch", value: "ch", label: "Switzerland" },
        cn: { name: "cn", value: "cn", label: "China" },
        co: { name: "co", value: "co", label: "Colombia" },
        cu: { name: "cu", value: "cu", label: "Cuba" },
        cz: { name: "cz", value: "cz", label: "Czech Republic" },
        de: { name: "de", value: "de", label: "Germany" },
        eg: { name: "eg", value: "eg", label: "Egypt" },
        fr: { name: "fr", value: "fr", label: "France" },
        gb: { name: "gb", value: "gb", label: "United Kingdom" },
        gr: { name: "gr", value: "gr", label: "Greece" },
        hk: { name: "hk", value: "hk", label: "Hong Kong" },
        hu: { name: "hu", value: "hu", label: "Hungary" },
        id: { name: "id", value: "id", label: "Indonesia" },
        ie: { name: "ie", value: "ie", label: "Ireland" },
        il: { name: "il", value: "il", label: "Israel" },
        in: { name: "in", value: "in", label: "India" },
        it: { name: "it", value: "it", label: "Italy" },
        jp: { name: "jp", value: "jp", label: "Japan" },
        kr: { name: "kr", value: "kr", label: "South Korea" },
        lt: { name: "lt", value: "lt", label: "Lithuania" },
        lv: { name: "lv", value: "lv", label: "Latvia" },
        ma: { name: "ma", value: "ma", label: "Morocco" },
        mx: { name: "mx", value: "mx", label: "Mexico" },
        my: { name: "my", value: "my", label: "Malaysia" },
        ng: { name: "ng", value: "ng", label: "Nigeria" },
        nl: { name: "nl", value: "nl", label: "Netherlands" },
        no: { name: "no", value: "no", label: "Norway" },
        nz: { name: "nz", value: "nz", label: "New Zealand" },
        ph: { name: "ph", value: "ph", label: "Philippines" },
        pl: { name: "pl", value: "pl", label: "Philippines" },
        pt: { name: "pt", value: "pt", label: "Poland" },
        ro: { name: "ro", value: "ro", label: "Portugal" },
        rs: { name: "rs", value: "rs", label: "Romania" },
        ru: { name: "ru", value: "ru", label: "Serbia" },
        sa: { name: "sa", value: "sa", label: "Russia" },
        se: { name: "se", value: "se", label: "Saudi Arabia" },
        sg: { name: "sg", value: "sg", label: "Sweden" },
        si: { name: "si", value: "si", label: "Singapore" },
        sk: { name: "sk", value: "sk", label: "Slovenia" },
        th: { name: "th", value: "th", label: "Slovakia" },
        tr: { name: "tr", value: "tr", label: "Thailand" },
        tw: { name: "tw", value: "tw", label: "Turkey" },
        ua: { name: "ua", value: "ua", label: "Taiwan" },
        us: { name: "us", value: "us", label: "United States" },
        ve: { label: "ve", value: "ve", label: "Venezuela" },
        za: { name: "za", value: "za", label: "South Africa" },
      },
    },
  },
  searchType: {
    everything: {
      name: "everything",
      label: "Everything",
      value: "everything",
      request: ["question", "from", "to", "sortBy"],
      response: [
        "source",
        "author",
        "title",
        "description",
        "url",
        "urlTolmage",
        "publishedAt",
        "content",
      ],
      responseTYpe: ["articles", "Status", "totalResults"],
    },
    topHeadLines: {
      name: "topHeadLines",
      label: "Top Headlines",
      value: "top-headlines",
      request: ["question", "country", "category", "sources"],
      response: [
        "source",
        "author",
        "title",
        "description",
        "url",
        "urlTolmage",
        "publishedAt",
        "content",
      ],
      responseTYpe: ["articles", "Status", "totalResults"],
    },
    sources: {
      name: "sources",
      label: "By Sources",
      value: "top-headlines/sources",
      request: ["country", "category", "language"],
      response: [
        "id",
        "name",
        "description",
        "url",
        "category",
        "language",
        "country",
      ],
      responseTYpe: ["sources", "Status"],
    },
  },
};

export default FormSearchModel;
